# Generated by Django 4.1 on 2022-09-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(blank=True)),
                ('score', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True, max_length=2500)),
                ('mode', models.CharField(blank=True, choices=[('regular', 'Regular'), ('part_time', 'Part_time'), ('remote', 'Remote')], default='regular', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
