# Generated by Django 4.1 on 2022-09-08 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
        ('superuser', '0001_initial'),
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='skills',
            field=models.ManyToManyField(to='superuser.skill'),
        ),
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='education.educationspecialisation'),
        ),
        migrations.AddField(
            model_name='education',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to='seeker.seekerprofile'),
        ),
    ]
