# Generated by Django 4.1 on 2022-10-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.companydepartment'),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='superuser.skill'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=150)),
                ('started_date', models.DateField()),
                ('ended_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile')),
            ],
        ),
    ]
