# Generated by Django 4.1 on 2022-09-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
        ('recruiter', '0003_alter_jobpost_roles'),
        ('seeker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seekerprofile'),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='superuser.skill'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='applied', max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobpost')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to='seeker.seekerprofile')),
            ],
        ),
    ]
