# Generated by Django 4.1 on 2022-10-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
        ('seeker', '0002_seekerprofile_department_alter_seekerprofile_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='superuser.skill'),
        ),
    ]
