# Generated by Django 4.1 on 2022-10-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0004_experience_current_ctc_experience_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='current_ctc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
