# Generated by Django 4.1 on 2022-10-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0005_alter_experience_current_ctc'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='domain_header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
