# Generated by Django 4.1 on 2022-09-16 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('superuser', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_logo', models.ImageField(blank=True, upload_to='media/<django.db.models.fields.CharField>/logo')),
                ('started_date', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=3000)),
                ('founder', models.CharField(blank=True, max_length=200)),
                ('ceo_name', models.CharField(blank=True, max_length=200)),
                ('ceo_image', models.ImageField(blank=True, upload_to='media/<django.db.models.fields.CharField>/ceo')),
                ('head_office_location', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superuser.companycategory')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('qualification_disc', models.CharField(blank=True, max_length=500)),
                ('roles', models.TextField(max_length=2000)),
                ('experience', models.IntegerField(null=True)),
                ('experience_desc', models.CharField(blank=True, max_length=500)),
                ('job_type', models.CharField(choices=[('remote', 'Remote'), ('in_office', 'In Office'), ('hybrid', 'Hybrid')], max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('salary_package', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.educationspecialisation')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiterprofile')),
                ('skills', models.ManyToManyField(to='superuser.skill')),
            ],
        ),
    ]
