# Generated by Django 4.1 on 2022-09-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='qualification',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='qualification',
            field=models.ManyToManyField(to='education.educationspecialisation'),
        ),
    ]
