# Generated by Django 4.1 on 2022-09-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_remove_jobpost_qualification_jobpost_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
