# Generated by Django 4.1 on 2022-09-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='roles',
            field=models.TextField(max_length=2000),
        ),
    ]
