# Generated by Django 4.1 on 2022-09-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_jobpost_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='salary_package',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='max_salary_package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='min_salary_package',
            field=models.IntegerField(null=True),
        ),
    ]
