# Generated by Django 4.1 on 2022-10-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_locations'),
        ('recruiter', '0004_remove_jobpost_salary_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superuser.locations'),
        ),
    ]
